name: Update badges from credly

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 */1 * *"
  pull_request:

jobs:
  update-readme:
    name: Update Readme with badges from credly
    runs-on: ubuntu-latest
    steps:
      - name: Update Readme with badges from credly
        uses: pemtajo/badge-readme@9e2802524f5361f1c3af4d99ea1247a7d5952687 # 3.2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update badges from credly"
          CREDLY_USER: engin-diri
